import "bootstrap-icons/font/bootstrap-icons.css";
import SessionProviderWrapper from "../components/SessionProviderWrapper";
import "./globals.css";

// import { DM_Sans } from "next/font/google";

// const dm_sans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <SessionProviderWrapper>{children}</SessionProviderWrapper>
      </body>
    </html>
  );
}
